[project]
name = "os_ai_llm"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3",
]

dependencies = [
  "httpx>=0.27",
]

[tool.uv]
package = true
