[project]
name = "os_ai_core"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3",
]

# runtime deps
dependencies = [
  "injector>=0.21.0",
  "pyautogui>=0.9.54",
  "Pillow>=10",
  "pyperclip>=1.8",
  # internal packages
  "os_ai_llm>=0.1.0",
  "os_ai_llm_anthropic>=0.1.0",
  "os_ai_llm_openai>=0.1.0",
  "os_ai_os>=0.1.0",
  # macOS drivers are only needed on Darwin; keep direct dep for mono repo dev
  "os_ai_os_macos>=0.1.0; platform_system == \"Darwin\"",
  # Windows drivers for Windows
  "os_ai_os_windows>=0.1.0; platform_system == \"Windows\"",
]

[tool.uv]
package = true
