[project]
name = "os_ai_llm_anthropic"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3",
]

dependencies = [
  "anthropic>=0.26.0",
  "httpx>=0.27",
  "os_ai_llm>=0.1.0",
  "os_ai_core>=0.1.0",
]

[tool.uv]
package = true
