[project]
name = "os_ai_llm_openai"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3",
]

dependencies = [
  "os_ai_llm>=0.1.0",
]

[tool.uv]
package = true
