[project]
name = "os_ai_cli"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
  "Programming Language :: Python :: 3",
]

# CLI depends on core to run orchestrator
dependencies = [
  "os_ai_core>=0.1.0",
]

[project.scripts]
os-ai = "os_ai_cli.main:main"

[tool.uv]
package = true
